name: Test & Lint #Название pipeline который будет выполнять github actions

on: [push]

jobs:
  tests:
    name: Tests
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test

  lint:
    name: Lint
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint:check